### ISSUE TITLE
Many broken things with 23.01.23

### ISSUE THREAD

**Issue by tflo** [frozn/TipTac#175]
23.01.23 seems badly broken:

- TipTac health bar is anchored to the screen (displayed in full screen width at the bottom of the screen)
- Addon interference: TipTac destroys the display of the WQAchievements standalone frame (background frame, plus overlapped by a separate tooltip-style frame)
- Addon interference: The SavedInstances tooltip gets over-scaled on second call.

This is just what I observed immediatly after updating TipTac (had to roll back to previous version), probably there are more glitches and interferences. Deactivating TipTac removes all symptoms described above. No errors logged in BugSack.

Let me know if you need more info, or screenshots.

Edit/PS: This is on Retail 100002.

**Comment by hollo6** [comment]
SavedInstances close button also disappears, already on first use.

**Comment by frozn** [comment]
I fixed many things with the latest release [v23.01.28](https://github.com/frozn/TipTac/releases/tag/v23.01.28-release).

Regarding addon SavedInstances: Some addons doesn't handle scaling properly. For LibDropdown-1.0 and LibDropdownMC-1.0 I opened a pull request on their GitHub page. Additionally I added the styling of these tooltips in TipTac which also handles the scaling itself in the latest release.

I installed SavedInstances for myself and I also have this misplaced close button you mentioned. This change in line 3612 in `\Core\Core.lua` of SavedInstances fixes this issue:

`self:SetSize(w * tooltip:GetScale() , (h+20) * tooltip:GetScale())`

to

`self:SetSize(w * tooltip:GetEffectiveScale() / UIParent:GetEffectiveScale(), h * tooltip:GetEffectiveScale() / UIParent:GetEffectiveScale() + 20 * tooltip:GetScale())`

To make this easy I created a pull request in their repository: https://github.com/SavedInstances/SavedInstances/pull/688

**Comment by tflo** [comment]
> SavedInstances […] Additionally I added the styling of these tooltips in TipTac which also handles the scaling itself in the latest release.

SavedInstances tooltip scaling is still bugged for me. Or is the "styling of these tooltips" an option I have to enable? (Haven't found one, so far.)
Anyways, let's hope they approve your pull request. 

Interference with **WQAchievements frame** is still there for me:

<img width="1248" alt="WoWScrnShot_012923_040938" src="https://user-images.githubusercontent.com/1410282/215302991-e416fb41-a649-4dc8-9c99-c23cb7b82afd.png">

Without TipTac (or with an older version of TipTac), this is just one frame, not 2 split frames like in the screenshot.

Also the **health bar** is still anchored to the screen bottom:


![WoWScrnShot_012923_041059](https://user-images.githubusercontent.com/1410282/215303155-0eacdaed-f5f3-48d9-a2bc-644e3de806a2.jpg)


See the health bar at the very bottom of the screen? It's the bar that normally is inside TipTac's tooltip frame. This happens also without any other addons enabled.

**Comment by tflo** [comment]
PS: 

For the interference problems with other addons, wouldn't it be a (sort of) solution to limit TipTac's tooltip modifications to the tooltips of action bar buttons, NPCs, world objects, unit frames, chat frame, etc., that is, not touching any other tooltips?

IIRC, TinyTooltips has/had an option for that ("Skin to more frames" or something similar)

**Comment by tflo** [comment]
PS2:

It seems the health bar anchoring has fixed itself, the bar is now back where it belongs to.

What did I do? I forgot to reinstall the pre-23.01.23 version of TipTac and just moved along after posting here, doing some WQs and stuff. So, actually I do not know what has fixed the issue (or if it will come back).

**Comment by TreizeEU** [comment]
After latest version of TipTac (v23.01.28), I still have the issue with Bulk Mail Inbox's scaling being increased.

**Comment by hollo6** [comment]
Also SavedInstances still gets huge after opening it for a second time (they fixed the misaligned close button but the scaling is still an issue).

**Comment by frozn** [comment]
I created a pull request for WQAchievements to fix the scaling issue: https://github.com/Urtgard/WQAchievements/pull/123

**Comment by frozn** [comment]
I created a pull request for Titan Panel Socialite to fix another scaling issue: https://github.com/solocommand/Socialite/pull/38

**Comment by tflo** [comment]
I have only played for an hour or two with your latest version (23.02.06), but so far all the issues from my OP seem to be fixed.

Many thanks for your hard work (and for creating the pull requests at others)!
