### ISSUE TITLE
LUA error when comparing items.

### ISSUE THREAD

**Issue by entroscopy** [frozn/TipTac#198]
Mousing over items in inventory while shift key is held throws an "attempt to perform arithmetic on a nil value" error for each item that is being compared with currently equipped items.

1. Log in and open your inventory
2. Press and hold shift
3. Mouse over items that can be compared with currently equipped items
![Unt](https://user-images.githubusercontent.com/30931739/216808930-29adf72f-0ab6-4d78-b598-34bfec0b5f26.jpg)

**TipTac Reborn**
 - Version 23.02.05

**WoW**
 - Flavor: WotLKC
 - Version 3.4.1

Doesn't happen with TipTac 23.01.28.

Error text:

```
Date: 2023-02-05 09:22:34
ID: 1
Error occured in: Global
Count: 1
Message: ...libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua line 259:
   attempt to perform arithmetic on a nil value
Debug:
   [string "@Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua"]:259: RefreshAnchorShoppingTooltips()
   [string "@Interface/AddOns/TipTac/ttCore.lua"]:2264:
      Interface/AddOns/TipTac/ttCore.lua:2262
   [string "=[C]"]: GameTooltip_ShowCompareItem()
   [string "@Interface/FrameXML/GameTooltip.lua"]:494:
      Interface/FrameXML/GameTooltip.lua:492
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Auc-Advanced/Libs/LibExtraTip/LibExtraTip.lua"]:502: OnTooltipSetItem()
   [string "@Interface/AddOns/Enchantrix/EnxMain.lua"]:240:
      Interface/AddOns/Enchantrix/EnxMain.lua:236
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Auc-Advanced/Libs/LibExtraTip/LibExtraTip.lua"]:428: SetBagItem()
   [string "@Interface/FrameXML/ContainerFrame_Shared.lua"]:1362: ContainerFrameItemButton_OnEnter()
   [string "@Interface/AddOns/BagBrother/addons/core/classes/item.lua"]:359: ShowTooltip()
   [string "@Interface/AddOns/BagBrother/addons/core/classes/item.lua"]:186:
      ...rface/AddOns/BagBrother/addons/core/classes/item.lua:182
Locals:
self = <table> {
 CreatePushArray = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:589
 GetAverageItemLevel = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:2142
 MixinDifferingObjects = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:724
 FormatText = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:381
 RegisterForGroupEvents = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:785
 GetValueFromObjectByPath = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:686
 MirrorAnchorPointCentered = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1149
 HookScriptOnTooltipSetItem = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:170
 IsAverageItemLevelAvailable = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:2114
 CallFunctionAndSuppressErrorMessageAndSpeech = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:662
 AreTalentsAvailable = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1964
 GetItemQualityColor = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:997
 CanInspect = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1746
 IsInspectFrameOpen = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1738
 RegisterNewSlashCommands = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:857
 IsTableEmpty = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:405
 RecalculateSizeOfGameTooltip = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1271
 InspectUnit = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1638
 CreateUnitRecord = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1539
 CreateMarkupForClassIcon = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1075
 UnitIsWildBattlePet = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:75
 UpdateUnitRecord = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1576
 ExistsInTable = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:598
 HookSecureFuncIfExists = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:755
 GetClassColorByClassFile = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:956
 UnitIsBattlePetCompanion = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:87
 GetUnitReactionIndex = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1439
 GetPowerColor = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:988
 FontExists = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1289
 TextureExists = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1316
 RemoveCallbackFromQueuedInspectCallbacks = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1684
 IsFrameBackInFrameChain = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1232
 CallFunctionDelayed = <function> defined @Interface/
AddOns:
  Swatter, v3.4.6921 (SwimmingSeadragon)
  AckisRecipeList, vv2.01-14-gfc58e9f
  Atlas, vv1.52.05
  AtlasBurningCrusade, vv1.52.01
  AtlasClassicWoW, vv1.52.01
  AtlasDungeonLocs, vv1.52.01
  AtlasTransportation, vv1.52.01
  AtlasWrathoftheLichKing, vv1.52.01
  AtlasLootClassic, vv3.1.1
  AtlasLootClassicData, vv3.1.1
  AtlasLootClassicDungeonsAndRaids, vv3.1.1
  AtlasQuest, v4.13.04
  Attune, v311
  AucAdvanced, v3.4.6931 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6941 (SwimmingSeadragon)
  AucScanData, v3.4.6908 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6928 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6913 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6910 (SwimmingSeadragon)
  AucStatSimple, v3.4.6911 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6912 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6914 (SwimmingSeadragon)
  BadBoy, vv10.0.1
  BadBoyCCleaner, vv10.0.1
  BadBoyHistory, vv10.0.1
  BagBrother, v
  Bagnon, v10.0.16
  BagnonScrap, v10
  CTCore, v10.0.2.5
  CTExpenseHistory, v9.2.0.3
  CTLibrary, v10.0.2.5
  DBMCore, vd98b338
  DBMStatusBarTimers, vd98b338
  DBMVPVEM, v3c03207
  Dominos, v10.0.19
  DominosProgress, v
  DominosRoll, v
  Enchantrix, v3.4.6942 (SwimmingSeadragon)
  EventHorizon, v22.11.08.0
  ExtendedCharacterStats, v3.0.9
  FasterLooting, v1.1.4
  FishingBuddy, v0.8.4
  GatherMate2, v1.47-classic
  Informant, v3.4.6934 (SwimmingSeadragon)
  MapCoords, v0.39
  Masque, v10.0.5
  MasqueCaith, v10.0.5
  MasqueDominos, vffa65c4
  MikScrollingBattleText, v5.7.154
  NeatPlates, vv429
  NeatPlatesGrey, v
  NeatPlatesHub, v
  NeatPlatesWidgets, v
  OmniCC, v10.0.4
  Postal, vv3.9.5
  Prat30, v3.9.19
  Prat30Libraries, v
  Quartz, v3.7.3
  QuestFrameFixer, v2.1
  QuestIconDesaturation, v3.3
  Questie, v7.4.12
  RareScanner, v3.4.1
  Recount, vv3.4.1b
  Scrap, v10.0.10
  SexyMap, vv10.0.10
  SlideBar, v3.4.6919 (SwimmingSeadragon)
  Stubby, v3.4.6920 (SwimmingSeadragon)
  TacoTip, v0.3.5
  ThreatClassic2, v2.47
  TipTac, v23.02.05
  TipTacItemRef, v23.02.05
  TomTom, vv3.3.5-release
  tullaRange, v10.0.11
  WeakAuras, v5.3.7
  XLoot, v10.0.2-2
  XLootFrame, v10.0.2-2
  ZPerl, v7.0.6
  ZPerlParty, v
  ZPerlPlayer, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v3.4.1.30401 <none>
  (ck=8ff)
```

**Comment by frozn** [comment]
Unfortunately I can't reproduce this. Which addon do you use for your bags?

But I have an idea what might be the problem. Could you try with this version?

[TipTac-dev.zip](https://github.com/frozn/TipTac/files/10610821/TipTac-dev.zip)

**Comment by entroscopy** [comment]
I'm using Bagnon. That version also gives errors for me. Might be something to do with auctioneer perhaps. I'll do more testing later to see if I can pinpoint the offending addon that's causing the issue.

**Comment by frozn** [comment]
This would be great to nail this further down!

I'm also using Bagon, but don't have this issue. 🤔

**Comment by entroscopy** [comment]
Yes, bagnon and tiptac work fine together. The errors start when auctioneer and tiptac are enabled together. Auctioneer seems to be the issue, or some component of it. This is with just tiptac and auctioneer enabled. 
![unt2](https://user-images.githubusercontent.com/30931739/216816918-c64226fd-8016-4c02-b104-6fdbbba07e00.jpg)

```
Date: 2023-02-05 12:46:34
ID: 1
Error occured in: Global
Count: 6
Message: ...libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua line 259:
   attempt to perform arithmetic on a nil value
Debug:
   [string "@Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua"]:259: RefreshAnchorShoppingTooltips()
   [string "@Interface/AddOns/TipTac/ttCore.lua"]:2266:
      Interface/AddOns/TipTac/ttCore.lua:2262
   [string "=[C]"]: GameTooltip_ShowCompareItem()
   [string "@Interface/FrameXML/GameTooltip.lua"]:494:
      Interface/FrameXML/GameTooltip.lua:492
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Auc-Advanced/Libs/LibExtraTip/LibExtraTip.lua"]:502:
      ...AddOns/Auc-Advanced/Libs/LibExtraTip/LibExtraTip.lua:496
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Auc-Advanced/Libs/LibExtraTip/LibExtraTip.lua"]:428: SetBagItem()
   [string "@Interface/FrameXML/ContainerFrame_Shared.lua"]:1362: ContainerFrameItemButton_OnEnter()
   [string "*ContainerFrame.xml:184_OnEnter"]:1:
      [string "*ContainerFrame.xml:184_OnEnter"]:1
Locals:
self = <table> {
 CreatePushArray = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:589
 GetAverageItemLevel = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:2142
 MixinDifferingObjects = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:724
 FormatText = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:381
 RegisterForGroupEvents = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:785
 GetValueFromObjectByPath = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:686
 MirrorAnchorPointCentered = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1149
 HookScriptOnTooltipSetItem = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:170
 IsAverageItemLevelAvailable = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:2114
 CallFunctionAndSuppressErrorMessageAndSpeech = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:662
 AreTalentsAvailable = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1964
 GetItemQualityColor = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:997
 CanInspect = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1746
 IsInspectFrameOpen = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1738
 RegisterNewSlashCommands = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:857
 IsTableEmpty = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:405
 RecalculateSizeOfGameTooltip = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1271
 InspectUnit = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1638
 CreateUnitRecord = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1539
 CreateMarkupForClassIcon = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1075
 UnitIsWildBattlePet = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:75
 UpdateUnitRecord = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1576
 ExistsInTable = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:598
 HookSecureFuncIfExists = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:755
 GetClassColorByClassFile = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:956
 UnitIsBattlePetCompanion = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:87
 GetUnitReactionIndex = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1439
 GetPowerColor = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:988
 FontExists = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1289
 TextureExists = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1316
 RemoveCallbackFromQueuedInspectCallbacks = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1684
 IsFrameBackInFrameChain = <function> defined @Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1232
 CallFunctionDelayed = <function> defined @Interface/
AddOns:
  Swatter, v3.4.6921 (SwimmingSeadragon)
  AucAdvanced, v3.4.6931 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6941 (SwimmingSeadragon)
  AucScanData, v3.4.6908 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6928 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6913 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6910 (SwimmingSeadragon)
  AucStatSimple, v3.4.6911 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6912 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6914 (SwimmingSeadragon)
  Stubby, v3.4.6920 (SwimmingSeadragon)
  TipTac, v23.02.05
  TipTacItemRef, v23.02.05
  TipTacTalents, v23.02.05
  BlizRuntimeLib_enUS v3.4.1.30401 <none>
  (ck=26e)
```

**Comment by hollo6** [comment]
Getting the (almost) same error in retail:

74x ...libs/LibFroznFunctions-1.0-4/LibFroznFunctions-1.0.lua:217: attempt to index local 'tip' (a nil value)
[string "@TipTac/libs/LibFroznFunctions-1.0-4/LibFroznFunctions-1.0.lua"]:217: in function `RefreshAnchorShoppingTooltips'
[string "@TipTac/ttCore.lua"]:2264: in function <TipTac/ttCore.lua:2262>
[string "=[C]"]: in function `GameTooltip_ShowCompareItem'
[string "@ArkInventory/Core/ArkInventory.lua"]:8930: in function `Frame_Item_OnEnter'
[string "*ArkInventory.xml:353_OnEnter"]:1: in function <[string "*ArkInventory.xml:353_OnEnter"]:1>

Locals:
self = <table> {
 CreatePushArray = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:589
 GetAverageItemLevel = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:2142
 MixinDifferingObjects = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:724
 FormatText = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:381
 RegisterForGroupEvents = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:785
 GetValueFromObjectByPath = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:686
 MirrorAnchorPointCentered = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1149
 HookScriptOnTooltipSetItem = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:170
 IsAverageItemLevelAvailable = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:2114
 CallFunctionAndSuppressErrorMessageAndSpeech = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:662
 AreTalentsAvailable = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1964
 GetItemQualityColor = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:997
 CanInspect = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1746
 IsInspectFrameOpen = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1738
 RegisterNewSlashCommands = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:857
 IsTableEmpty = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:405
 RecalculateSizeOfGameTooltip = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1271
 InspectUnit = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1638
 CreateUnitRecord = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1539
 CreateMarkupForClassIcon = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1075
 UnitIsWildBattlePet = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:75
 UpdateUnitRecord = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1576
 ExistsInTable = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:598
 HookSecureFuncIfExists = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:755
 GetClassColorByClassFile = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:956
 UnitIsBattlePetCompanion = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:87
 GetUnitReactionIndex = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1439
 GetPowerColor = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:988
 FontExists = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1289
 TextureExists = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1316
 RemoveCallbackFromQueuedInspectCallbacks = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1684
 IsFrameBackInFrameChain = <function> defined @TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:1232
 CallFunctionDelayed = <function> defined @

**Comment by hollo6** [comment]
Your attached dev version seems to fix it.

**Comment by frozn** [comment]
I also fixed the error in combination with Auctioneer addon. Here's the dev version:

[TipTac-dev.zip](https://github.com/frozn/TipTac/files/10611623/TipTac-dev.zip)

Working fine for ou, too @entroscopy?

**Comment by entroscopy** [comment]
Hi, that one seems to have fixed issues with the inventory for me, but I just noticed another error when comparing items at a merchant. Only seems to happen when mousing over weapons and trinkets with shift.
![Unt3](https://user-images.githubusercontent.com/30931739/216836793-9bb77028-3f71-4690-af42-ba7b036363c8.jpg)

Disabling auctioneer doesn't fix this one. Haven't tried disabling other addons since I have a raid coming up. Can do that later if you need me to.

```
Date: 2023-02-05 18:52:57
ID: 1
Error occured in: Global
Count: ∞
Message: ...libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua line 334:
   Action[SetPoint] failed because[Cannot anchor to itself]: attempted from: ShoppingTooltip2:SetPoint.
Debug:
   [string "=[C]"]: SetPoint()
   [string "@Interface/AddOns/TipTac/libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua"]:334: RefreshAnchorShoppingTooltips()
   [string "@Interface/AddOns/TipTac/ttCore.lua"]:2266:
      Interface/AddOns/TipTac/ttCore.lua:2262
   [string "=[C]"]: GameTooltip_ShowCompareItem()
   [string "@Interface_TBC/FrameXML/MerchantFrame.lua"]:623: MerchantItemButton_OnEnter()
   [string "*MerchantFrame.xml:47_OnEnter"]:1:
      [string "*MerchantFrame.xml:47_OnEnter"]:1
Locals:
(*temporary) = ShoppingTooltip2 {
 0 = <userdata>
 ttSetIconTextureAndText = <function> defined @Interface/AddOns/TipTacItemRef/ttItemRef.lua:198
 SetSpellBookItem = <function> defined =[C]:-1
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetHyperlink = <function> defined =[C]:-1
 SetTradeSkillItem = <function> defined =[C]:-1
 SetBackdropBorderColor = <function> defined =[C]:-1
 RightEdge = Texture {
 }
 SetCraftItem = <function> defined =[C]:-1
 ApplyBackdrop = <function> defined =[C]:-1
 SetBackdrop = <function> defined =[C]:-1
 ClearBackdrop = <function> defined =[C]:-1
 TopOverlay = Texture {
 }
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 SetUnitDebuff = <function> defined =[C]:-1
 __hasCounters = true
 SetQuestItem = <function> defined =[C]:-1
 SetUnit = <function> defined =[C]:-1
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 FadeOut = <function> defined =[C]:-1
 Center = Texture {
 }
 LeftEdge = Texture {
 }
 BottomEdge = Texture {
 }
 SetQuestCurrency = <function> defined =[C]:-1
 BottomRightCorner = Texture {
 }
 BottomLeftCorner = Texture {
 }
 TopRightCorner = Texture {
 }
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 TopLeftCorner = Texture {
 }
 backdropInfo = <table> {
 }
 SetQuestLogItem = <function> defined =[C]:-1
 ttIcon = Texture {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 updateTooltip = 0.200000
 SetUnitBuff = <function> defined =[C]:-1
 TopEdge = Texture {
 }
 ttCount = FontString {
 }
 TooltipBackdropOnLoad = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:172
 SetUnitAura = <function> defined =[C]:-1
 NineSlice = Frame {
 }
 SetPetAction = <function> defined =[C]:-1
 SetAction = <function> defined =[C]:-1
 needsReset = true
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined =[C]:-1
 SetQuestLogCurrency = <function> defined =[C]:-1
 BottomOverlay = Texture {
 }
}
(*temporary) = "TOP"
(*temporary) = ShoppingTooltip2 {
 0 = <userdata>
 ttSetIconTextureAndText = <function> defined @Interface/AddOns/TipTacItemRef/ttItemRef.lua:198
 SetSpellBookItem = <function> defined =[C]:-1
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetHyperlink = <function> defined =[C]:-1
 SetTradeSkillItem = <function> defined =[C]:-1
 SetBackdropBorderColor = <function> defined =[C]:-1
 RightEdge = Texture {
 }
 SetCraftItem = <function> defined =[C]:-1
 ApplyBackdrop = <function> defined =[C]:-1
 SetBackdrop = <function> defined =[C]:-1
 ClearBackdrop = <function> defined =[C]:-1
 TopOverlay = Texture {
 }
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 SetUnitDebuff = <function> defined =[C]:-1
 __hasCounters = true
 SetQuestItem = <function> defined =[C]:-1
 SetUnit = <function> defined =[C]:-1
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 FadeOut = <function> defined =[C]:-1
 Center = Texture {
 }
 LeftEdge = Texture {
 }
 BottomEdge = Texture {
 }
 SetQuestCurrency = <function> defined =[C]:-1
 BottomRightCorner = Texture {
 }
 BottomLeftCorner = Texture {
 }
 TopRightCorner = Texture {
 }
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 TopLeftCorner = Texture {
 }
 backdropInfo = <table> {
 }
 SetQuestLogItem = <function>
AddOns:
  Swatter, v3.4.6921 (SwimmingSeadragon)
  AckisRecipeList, vv2.01-14-gfc58e9f
  Atlas, vv1.52.05
  AtlasBurningCrusade, vv1.52.01
  AtlasClassicWoW, vv1.52.01
  AtlasDungeonLocs, vv1.52.01
  AtlasTransportation, vv1.52.01
  AtlasWrathoftheLichKing, vv1.52.01
  AtlasLootClassic, vv3.1.1
  AtlasLootClassicData, vv3.1.1
  AtlasLootClassicDungeonsAndRaids, vv3.1.1
  AtlasQuest, v4.13.04
  BadBoy, vv10.0.1
  BadBoyCCleaner, vv10.0.1
  BadBoyHistory, vv10.0.1
  BagBrother, v
  Bagnon, v10.0.16
  BagnonScrap, v10
  CTCore, v10.0.2.5
  CTExpenseHistory, v9.2.0.3
  CTLibrary, v10.0.2.5
  DBMCore, vd98b338
  DBMStatusBarTimers, vd98b338
  DBMVPVEM, v3c03207
  Dominos, v10.0.19
  DominosProgress, v
  EventHorizon, v22.11.08.0
  ExtendedCharacterStats, v3.0.9
  FasterLooting, v1.1.4
  FishingBuddy, v0.8.4
  GatherMate2, v1.47-classic
  kgPanels, v1.4.4
  MapCoords, v0.39
  Masque, v10.0.5
  MasqueCaith, v10.0.5
  MikScrollingBattleText, v5.7.154
  NeatPlates, vv429
  NeatPlatesGrey, v
  NeatPlatesHub, v
  NeatPlatesWidgets, v
  OmniCC, v10.0.4
  Postal, vv3.9.5
  Prat30, v3.9.19
  Prat30Libraries, v
  Quartz, v3.7.3
  QuestFrameFixer, v2.1
  QuestIconDesaturation, v3.3
  Questie, v7.4.12
  RareScanner, v3.4.1
  Recount, vv3.4.1b
  Scrap, v10.0.10
  ScrapMerchant, v
  SexyMap, vv10.0.10
  SimpleInterruptAnnounce, v1.0.0
  SlideBar, v3.4.6919 (SwimmingSeadragon)
  Stubby, v3.4.6920 (SwimmingSeadragon)
  TacoTip, v0.3.5
  ThreatClassic2, v2.47
  TipTac, v23.02.05
  TipTacItemRef, v23.02.05
  TomTom, vv3.3.5-release
  tullaRange, v10.0.11
  WeakAuras, v5.3.7
  XLoot, v10.0.2-2
  XLootFrame, v10.0.2-2
  ZPerl, v7.0.6
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerPet, v
  ZPerlRaidFrames, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v3.4.1.30401 <none>
  (ck=71f)
```

**Comment by frozn** [comment]
I finally has been able to find the cause of this error message. It only happens under WotLKC if 2 additional comparing tooltips (e.g. on rings/trinkets) expands on the right side of the original tooltip. This was a tricky one. 🙈

Pushed out all fixes regarding comparing items with today's release ([v23.02.06](https://github.com/frozn/TipTac/releases/tag/v23.02.06-release)).

**Comment by entroscopy** [comment]
That did it. Thanks for the speedy fixes, especially on a weekend!
